import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../store"; // Adjust the import path based on where your store is

// Define the initial state
interface ModalState {
  show: boolean;
  for: string | null;
  data: { [key: string]: string } | null;
}

const initialState: ModalState = {
  show: false,
  for: null,
  data: null,
};

// Create the slice
const modalSlice = createSlice({
  name: "modal",
  initialState,
  reducers: {
    openModal(state) {
      state.show = true;
    },
    closeModal(state) {
      state.show = false;
    },
    initRenameAssetModal(state, action) {
      state.show = true;
      state.for = "ASSET_OPTIONS";
      state.data = { url: action.payload.url };
    },
  },
});

// Export the actions generated by createSlice
export const { openModal, closeModal, initRenameAssetModal } = modalSlice.actions;

// Selectors
export const selectShowModal = (state: RootState) => state.modal.show;
export const selectModalFor = (state: RootState) => state.modal.for;
export const selectModalData = (state: RootState) => state.modal.data;

// Export the reducer to be added to the store
export default modalSlice.reducer;
