import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleSignInInit } from "./components/GoogleSignInInit";
import Head from 'next/head';
import StoreProvider from "./lib/redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
        <link rel='preconnect' href='https://pomf2.lain.la/' />
        <link rel='dns-prefetch' href='https://pomf2.lain.la/' />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <StoreProvider>{children}</StoreProvider>
        <GoogleSignInInit />
      </body>
    </html>
  );
}
